from __future__ import annotations
from kudi.currency_codes import CurrencyCode
from typing import TypedDict

from kudi.exceptions import InvalidCurrencyNumericCodeError


class CurrencyData(TypedDict):
    numeric_code: str
    minor_unit: int
    symbol: str
    template: str
    minor_unit_separator: str
    thousand_delimiter: str


def _get_numeric_code(code: CurrencyCode) -> str:
    return CURRENCIES_DATA[code]["numeric_code"]


def _get_currency_code_from_numeric_code(numeric_code: str) -> CurrencyCode:
    for currency_code, currency_data in CURRENCIES_DATA.items():
        if currency_data["numeric_code"] == numeric_code:
            return currency_code
    raise InvalidCurrencyNumericCodeError(
        f"`{numeric_code}` is an invalid numeric currency code, please use 3-digit ISO code e.g.`840` for `USD`"
    )


CURRENCIES_DATA: dict[CurrencyCode, CurrencyData] = {
    CurrencyCode.AED: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "784",
        "symbol": ".\u062f.\u0625",
        "template": "1 $",
    },
    CurrencyCode.AFN: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "971",
        "symbol": "\u060b",
        "template": "1 $",
    },
    CurrencyCode.ALL: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "008",
        "symbol": "L",
        "template": "$1",
    },
    CurrencyCode.AMD: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "051",
        "symbol": "\u0564\u0580.",
        "template": "1 $",
    },
    CurrencyCode.ANG: {
        "minor_unit_separator": ",",
        "thousand_delimiter": ".",
        "minor_unit": 2,
        "numeric_code": "532",
        "symbol": "\u0192",
        "template": "$1",
    },
    CurrencyCode.AOA: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "973",
        "symbol": "Kz",
        "template": "1$",
    },
    CurrencyCode.ARS: {
        "minor_unit_separator": ",",
        "thousand_delimiter": ".",
        "minor_unit": 2,
        "numeric_code": "032",
        "symbol": "$",
        "template": "$1",
    },
    CurrencyCode.AUD: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "036",
        "symbol": "A$",
        "template": "$1",
    },
    CurrencyCode.AWG: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "533",
        "symbol": "\u0192",
        "template": "1$",
    },
    CurrencyCode.AZN: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "944",
        "symbol": "\u20bc",
        "template": "$1",
    },
    CurrencyCode.BAM: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "977",
        "symbol": "KM",
        "template": "$1",
    },
    CurrencyCode.BBD: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "052",
        "symbol": "$",
        "template": "$1",
    },
    CurrencyCode.BDT: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "050",
        "symbol": "\u09f3",
        "template": "$1",
    },
    CurrencyCode.BGN: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "975",
        "symbol": "\u043b\u0432",
        "template": "$1",
    },
    CurrencyCode.BHD: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 3,
        "numeric_code": "048",
        "symbol": ".\u062f.\u0628",
        "template": "1 $",
    },
    CurrencyCode.BIF: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 0,
        "numeric_code": "108",
        "symbol": "Fr",
        "template": "1$",
    },
    CurrencyCode.BMD: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "060",
        "symbol": "$",
        "template": "$1",
    },
    CurrencyCode.BND: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "096",
        "symbol": "$",
        "template": "$1",
    },
    CurrencyCode.BOB: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "068",
        "symbol": "Bs.",
        "template": "$1",
    },
    CurrencyCode.BRL: {
        "minor_unit_separator": ",",
        "thousand_delimiter": ".",
        "minor_unit": 2,
        "numeric_code": "986",
        "symbol": "R$",
        "template": "$1",
    },
    CurrencyCode.BSD: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "044",
        "symbol": "$",
        "template": "$1",
    },
    CurrencyCode.BTN: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "064",
        "symbol": "Nu.",
        "template": "1$",
    },
    CurrencyCode.BWP: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "072",
        "symbol": "P",
        "template": "$1",
    },
    CurrencyCode.BYN: {
        "minor_unit_separator": ",",
        "thousand_delimiter": " ",
        "minor_unit": 2,
        "numeric_code": "933",
        "symbol": "p.",
        "template": "1 $",
    },
    CurrencyCode.BYR: {
        "minor_unit_separator": ",",
        "thousand_delimiter": " ",
        "minor_unit": 0,
        "numeric_code": "",
        "symbol": "p.",
        "template": "1 $",
    },
    CurrencyCode.BZD: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "084",
        "symbol": "BZ$",
        "template": "$1",
    },
    CurrencyCode.CAD: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "124",
        "symbol": "$",
        "template": "$1",
    },
    CurrencyCode.CDF: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "976",
        "symbol": "FC",
        "template": "1$",
    },
    CurrencyCode.CHF: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "756",
        "symbol": "CHF",
        "template": "1 $",
    },
    CurrencyCode.CLF: {
        "minor_unit_separator": ",",
        "thousand_delimiter": ".",
        "minor_unit": 4,
        "numeric_code": "990",
        "symbol": "UF",
        "template": "$1",
    },
    CurrencyCode.CLP: {
        "minor_unit_separator": ",",
        "thousand_delimiter": ".",
        "minor_unit": 0,
        "numeric_code": "152",
        "symbol": "$",
        "template": "$1",
    },
    CurrencyCode.CNY: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "156",
        "symbol": "\u5143",
        "template": "1 $",
    },
    CurrencyCode.COP: {
        "minor_unit_separator": ",",
        "thousand_delimiter": ".",
        "minor_unit": 2,
        "numeric_code": "170",
        "symbol": "$",
        "template": "$1",
    },
    CurrencyCode.CRC: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "188",
        "symbol": "\u20a1",
        "template": "$1",
    },
    CurrencyCode.CUC: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "931",
        "symbol": "$",
        "template": "1$",
    },
    CurrencyCode.CUP: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "192",
        "symbol": "$MN",
        "template": "$1",
    },
    CurrencyCode.CVE: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "132",
        "symbol": "$",
        "template": "1$",
    },
    CurrencyCode.CZK: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "203",
        "symbol": "K\u010d",
        "template": "1 $",
    },
    CurrencyCode.DJF: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 0,
        "numeric_code": "262",
        "symbol": "Fdj",
        "template": "1 $",
    },
    CurrencyCode.DKK: {
        "minor_unit_separator": ",",
        "thousand_delimiter": ".",
        "minor_unit": 2,
        "numeric_code": "208",
        "symbol": "kr",
        "template": "$ 1",
    },
    CurrencyCode.DOP: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "214",
        "symbol": "RD$",
        "template": "$1",
    },
    CurrencyCode.DZD: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "012",
        "symbol": ".\u062f.\u062c",
        "template": "1 $",
    },
    CurrencyCode.EEK: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "",
        "symbol": "kr",
        "template": "$1",
    },
    CurrencyCode.EGP: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "818",
        "symbol": "\u00a3",
        "template": "$1",
    },
    CurrencyCode.ERN: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "232",
        "symbol": "Nfk",
        "template": "1 $",
    },
    CurrencyCode.ETB: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "230",
        "symbol": "Br",
        "template": "1 $",
    },
    CurrencyCode.EUR: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "978",
        "symbol": "\u20ac",
        "template": "$1",
    },
    CurrencyCode.FJD: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "242",
        "symbol": "$",
        "template": "$1",
    },
    CurrencyCode.FKP: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "238",
        "symbol": "\u00a3",
        "template": "$1",
    },
    CurrencyCode.GBP: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "826",
        "symbol": "\u00a3",
        "template": "$1",
    },
    CurrencyCode.GEL: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "981",
        "symbol": "\u10da",
        "template": "1 $",
    },
    CurrencyCode.GGP: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "",
        "symbol": "\u00a3",
        "template": "$1",
    },
    CurrencyCode.GHC: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "",
        "symbol": "\u00a2",
        "template": "$1",
    },
    CurrencyCode.GHS: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "936",
        "symbol": "\u20b5",
        "template": "$1",
    },
    CurrencyCode.GIP: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "292",
        "symbol": "\u00a3",
        "template": "$1",
    },
    CurrencyCode.GMD: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "270",
        "symbol": "D",
        "template": "1 $",
    },
    CurrencyCode.GNF: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 0,
        "numeric_code": "324",
        "symbol": "FG",
        "template": "1 $",
    },
    CurrencyCode.GTQ: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "320",
        "symbol": "Q",
        "template": "$1",
    },
    CurrencyCode.GYD: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "328",
        "symbol": "$",
        "template": "$1",
    },
    CurrencyCode.HKD: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "344",
        "symbol": "HK$",
        "template": "$1",
    },
    CurrencyCode.HNL: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "340",
        "symbol": "L",
        "template": "$1",
    },
    CurrencyCode.HRK: {
        "minor_unit_separator": ",",
        "thousand_delimiter": ".",
        "minor_unit": 2,
        "numeric_code": "191",
        "symbol": "kn",
        "template": "1 $",
    },
    CurrencyCode.HTG: {
        "minor_unit_separator": ",",
        "thousand_delimiter": ".",
        "minor_unit": 2,
        "numeric_code": "332",
        "symbol": "G",
        "template": "1 $",
    },
    CurrencyCode.HUF: {
        "minor_unit_separator": ",",
        "thousand_delimiter": ".",
        "minor_unit": 2,
        "numeric_code": "348",
        "symbol": "Ft",
        "template": "1 $",
    },
    CurrencyCode.IDR: {
        "minor_unit_separator": ",",
        "thousand_delimiter": ".",
        "minor_unit": 2,
        "numeric_code": "360",
        "symbol": "Rp",
        "template": "$1",
    },
    CurrencyCode.ILS: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "376",
        "symbol": "\u20aa",
        "template": "$1",
    },
    CurrencyCode.IMP: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "",
        "symbol": "\u00a3",
        "template": "$1",
    },
    CurrencyCode.INR: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "356",
        "symbol": "\u20b9",
        "template": "$1",
    },
    CurrencyCode.IQD: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 3,
        "numeric_code": "368",
        "symbol": ".\u062f.\u0639",
        "template": "1 $",
    },
    CurrencyCode.IRR: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "364",
        "symbol": "\ufdfc",
        "template": "1 $",
    },
    CurrencyCode.ISK: {
        "minor_unit_separator": ",",
        "thousand_delimiter": ".",
        "minor_unit": 0,
        "numeric_code": "352",
        "symbol": "kr",
        "template": "$1",
    },
    CurrencyCode.JEP: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "",
        "symbol": "\u00a3",
        "template": "$1",
    },
    CurrencyCode.JMD: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "388",
        "symbol": "J$",
        "template": "$1",
    },
    CurrencyCode.JOD: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 3,
        "numeric_code": "400",
        "symbol": ".\u062f.\u0625",
        "template": "1 $",
    },
    CurrencyCode.JPY: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 0,
        "numeric_code": "392",
        "symbol": "\u00a5",
        "template": "$1",
    },
    CurrencyCode.KES: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "404",
        "symbol": "KSh",
        "template": "$1",
    },
    CurrencyCode.KGS: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "417",
        "symbol": "\u0441\u043e\u043c",
        "template": "1 $",
    },
    CurrencyCode.KHR: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "116",
        "symbol": "\u17db",
        "template": "$1",
    },
    CurrencyCode.KMF: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 0,
        "numeric_code": "174",
        "symbol": "CF",
        "template": "$1",
    },
    CurrencyCode.KPW: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "408",
        "symbol": "\u20a9",
        "template": "$1",
    },
    CurrencyCode.KRW: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 0,
        "numeric_code": "410",
        "symbol": "\u20a9",
        "template": "$1",
    },
    CurrencyCode.KWD: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 3,
        "numeric_code": "414",
        "symbol": ".\u062f.\u0643",
        "template": "1 $",
    },
    CurrencyCode.KYD: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "136",
        "symbol": "$",
        "template": "$1",
    },
    CurrencyCode.KZT: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "398",
        "symbol": "\u20b8",
        "template": "$1",
    },
    CurrencyCode.LAK: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "418",
        "symbol": "\u20ad",
        "template": "$1",
    },
    CurrencyCode.LBP: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "422",
        "symbol": "\u00a3",
        "template": "$1",
    },
    CurrencyCode.LKR: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "144",
        "symbol": "\u20a8",
        "template": "$1",
    },
    CurrencyCode.LRD: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "430",
        "symbol": "$",
        "template": "$1",
    },
    CurrencyCode.LSL: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "426",
        "symbol": "L",
        "template": "$1",
    },
    CurrencyCode.LTL: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "",
        "symbol": "Lt",
        "template": "$1",
    },
    CurrencyCode.LVL: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "",
        "symbol": "Ls",
        "template": "1 $",
    },
    CurrencyCode.LYD: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 3,
        "numeric_code": "434",
        "symbol": ".\u062f.\u0644",
        "template": "1 $",
    },
    CurrencyCode.MAD: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "504",
        "symbol": ".\u062f.\u0645",
        "template": "1 $",
    },
    CurrencyCode.MDL: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "498",
        "symbol": "lei",
        "template": "1 $",
    },
    CurrencyCode.MGA: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "969",
        "symbol": "Ar",
        "template": "1$",
    },
    CurrencyCode.MKD: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "807",
        "symbol": "\u0434\u0435\u043d",
        "template": "$1",
    },
    CurrencyCode.MMK: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "104",
        "symbol": "K",
        "template": "$1",
    },
    CurrencyCode.MNT: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "496",
        "symbol": "\u20ae",
        "template": "$1",
    },
    CurrencyCode.MOP: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "446",
        "symbol": "P",
        "template": "1 $",
    },
    CurrencyCode.MRU: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "929",
        "symbol": "UM",
        "template": "$1",
    },
    CurrencyCode.MUR: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "480",
        "symbol": "\u20a8",
        "template": "$1",
    },
    CurrencyCode.MVR: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "462",
        "symbol": "MVR",
        "template": "1 $",
    },
    CurrencyCode.MWK: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "454",
        "symbol": "MK",
        "template": "$1",
    },
    CurrencyCode.MXN: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "484",
        "symbol": "$",
        "template": "$1",
    },
    CurrencyCode.MYR: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "458",
        "symbol": "RM",
        "template": "$1",
    },
    CurrencyCode.MZN: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "943",
        "symbol": "MT",
        "template": "$1",
    },
    CurrencyCode.NAD: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "516",
        "symbol": "$",
        "template": "$1",
    },
    CurrencyCode.NGN: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "566",
        "symbol": "\u20a6",
        "template": "$1",
    },
    CurrencyCode.NIO: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "558",
        "symbol": "C$",
        "template": "$1",
    },
    CurrencyCode.NOK: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "578",
        "symbol": "kr",
        "template": "1 $",
    },
    CurrencyCode.NPR: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "524",
        "symbol": "\u20a8",
        "template": "$1",
    },
    CurrencyCode.NZD: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "554",
        "symbol": "$",
        "template": "$1",
    },
    CurrencyCode.OMR: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 3,
        "numeric_code": "512",
        "symbol": "\ufdfc",
        "template": "1 $",
    },
    CurrencyCode.PAB: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "590",
        "symbol": "B/.",
        "template": "$1",
    },
    CurrencyCode.PEN: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "604",
        "symbol": "S/",
        "template": "$1",
    },
    CurrencyCode.PGK: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "598",
        "symbol": "K",
        "template": "1 $",
    },
    CurrencyCode.PHP: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "608",
        "symbol": "\u20b1",
        "template": "$1",
    },
    CurrencyCode.PKR: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "586",
        "symbol": "\u20a8",
        "template": "$1",
    },
    CurrencyCode.PLN: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "985",
        "symbol": "z\u0142",
        "template": "1 $",
    },
    CurrencyCode.PYG: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 0,
        "numeric_code": "600",
        "symbol": "Gs",
        "template": "1$",
    },
    CurrencyCode.QAR: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "634",
        "symbol": "\ufdfc",
        "template": "1 $",
    },
    CurrencyCode.RON: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "946",
        "symbol": "lei",
        "template": "$1",
    },
    CurrencyCode.RSD: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "941",
        "symbol": "\u0414\u0438\u043d.",
        "template": "$1",
    },
    CurrencyCode.RUB: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "643",
        "symbol": "\u20bd",
        "template": "1 $",
    },
    CurrencyCode.RUR: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "",
        "symbol": "\u20bd",
        "template": "1 $",
    },
    CurrencyCode.RWF: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 0,
        "numeric_code": "646",
        "symbol": "FRw",
        "template": "1 $",
    },
    CurrencyCode.SAR: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "682",
        "symbol": "\ufdfc",
        "template": "1 $",
    },
    CurrencyCode.SBD: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "090",
        "symbol": "$",
        "template": "$1",
    },
    CurrencyCode.SCR: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "690",
        "symbol": "\u20a8",
        "template": "$1",
    },
    CurrencyCode.SDG: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "938",
        "symbol": "\u00a3",
        "template": "$1",
    },
    CurrencyCode.SEK: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "752",
        "symbol": "kr",
        "template": "1 $",
    },
    CurrencyCode.SGD: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "702",
        "symbol": "S$",
        "template": "$1",
    },
    CurrencyCode.SHP: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "654",
        "symbol": "\u00a3",
        "template": "$1",
    },
    CurrencyCode.SKK: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "",
        "symbol": "Sk",
        "template": "$1",
    },
    CurrencyCode.SLE: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "925",
        "symbol": "Le",
        "template": "1 $",
    },
    CurrencyCode.SLL: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "694",
        "symbol": "Le",
        "template": "1 $",
    },
    CurrencyCode.SOS: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "706",
        "symbol": "Sh",
        "template": "1 $",
    },
    CurrencyCode.SRD: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "968",
        "symbol": "$",
        "template": "$1",
    },
    CurrencyCode.SSP: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "728",
        "symbol": "\u00a3",
        "template": "1 $",
    },
    CurrencyCode.STD: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "",
        "symbol": "Db",
        "template": "1 $",
    },
    CurrencyCode.STN: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "930",
        "symbol": "Db",
        "template": "1 $",
    },
    CurrencyCode.SVC: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "222",
        "symbol": "\u20a1",
        "template": "$1",
    },
    CurrencyCode.SYP: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "760",
        "symbol": "\u00a3",
        "template": "1 $",
    },
    CurrencyCode.SZL: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "748",
        "symbol": "\u00a3",
        "template": "$1",
    },
    CurrencyCode.THB: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "764",
        "symbol": "\u0e3f",
        "template": "$1",
    },
    CurrencyCode.TJS: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "972",
        "symbol": "SM",
        "template": "1 $",
    },
    CurrencyCode.TMT: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "934",
        "symbol": "T",
        "template": "1 $",
    },
    CurrencyCode.TND: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 3,
        "numeric_code": "788",
        "symbol": ".\u062f.\u062a",
        "template": "1 $",
    },
    CurrencyCode.TOP: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "776",
        "symbol": "T$",
        "template": "$1",
    },
    CurrencyCode.TRL: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "",
        "symbol": "\u20a4",
        "template": "$1",
    },
    CurrencyCode.TRY: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "949",
        "symbol": "\u20ba",
        "template": "$1",
    },
    CurrencyCode.TTD: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "780",
        "symbol": "TT$",
        "template": "$1",
    },
    CurrencyCode.TWD: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "901",
        "symbol": "NT$",
        "template": "$1",
    },
    CurrencyCode.TZS: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "834",
        "symbol": "TSh",
        "template": "$1",
    },
    CurrencyCode.UAH: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "980",
        "symbol": "\u20b4",
        "template": "1 $",
    },
    CurrencyCode.UGX: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 0,
        "numeric_code": "800",
        "symbol": "USh",
        "template": "1 $",
    },
    CurrencyCode.USD: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "840",
        "symbol": "$",
        "template": "$1",
    },
    CurrencyCode.UYU: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "858",
        "symbol": "$U",
        "template": "$1",
    },
    CurrencyCode.UZS: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "860",
        "symbol": "so\u2019m",
        "template": "$1",
    },
    CurrencyCode.VEF: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "937",
        "symbol": "Bs",
        "template": "$1",
    },
    CurrencyCode.VES: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "928",
        "symbol": "Bs.S",
        "template": "$1",
    },
    CurrencyCode.VND: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 0,
        "numeric_code": "704",
        "symbol": "\u20ab",
        "template": "1 $",
    },
    CurrencyCode.VUV: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 0,
        "numeric_code": "548",
        "symbol": "Vt",
        "template": "$1",
    },
    CurrencyCode.WST: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "882",
        "symbol": "T",
        "template": "1 $",
    },
    CurrencyCode.XAF: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 0,
        "numeric_code": "950",
        "symbol": "Fr",
        "template": "1 $",
    },
    CurrencyCode.XAG: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 0,
        "numeric_code": "961",
        "symbol": "oz t",
        "template": "1 $",
    },
    CurrencyCode.XAU: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 0,
        "numeric_code": "959",
        "symbol": "oz t",
        "template": "1 $",
    },
    CurrencyCode.XCD: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "951",
        "symbol": "$",
        "template": "$1",
    },
    CurrencyCode.XCG: {
        "minor_unit_separator": ",",
        "thousand_delimiter": ".",
        "minor_unit": 2,
        "numeric_code": "532",
        "symbol": "Cg",
        "template": "$1",
    },
    CurrencyCode.XDR: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 0,
        "numeric_code": "960",
        "symbol": "SDR",
        "template": "1 $",
    },
    CurrencyCode.XOF: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 0,
        "numeric_code": "952",
        "symbol": "CFA",
        "template": "1 $",
    },
    CurrencyCode.XPF: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 0,
        "numeric_code": "953",
        "symbol": "₣",
        "template": "1 $",
    },
    CurrencyCode.YER: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "886",
        "symbol": "\ufdfc",
        "template": "1 $",
    },
    CurrencyCode.ZAR: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "710",
        "symbol": "R",
        "template": "$1",
    },
    CurrencyCode.ZMW: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "967",
        "symbol": "ZK",
        "template": "$1",
    },
    CurrencyCode.ZWD: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "716",
        "symbol": "Z$",
        "template": "$1",
    },
    CurrencyCode.ZWL: {
        "minor_unit_separator": ".",
        "thousand_delimiter": ",",
        "minor_unit": 2,
        "numeric_code": "932",
        "symbol": "Z$",
        "template": "$1",
    },
}
